version: '3'

services:
  flask-app:
    build: .
    volumes:
      - ./data:/app/data  # Mounts a local directory to store messages
      - ./templates:/app/templates  # Mounts the templates directory
      - ./static:/app/static  # Mounts the static directory
    ports:
      - "5010:5000"
    environment:
      FLASK_ENV: development

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "87:80"
    depends_on:
      - flask-app
